### ISSUE TITLE
Zot2Bib does not seem to work with Zotero 5.0

### ISSUE THREAD

**Issue by nathan-artist** [jawj/Zot2Bib#2]
Zot2Bib does not seem to work with Zotero 5.0. The [announcement for Zotero 5.0](https://www.zotero.org/blog/zotero-5-0/) (2017-07-10) says: "Zotero 5.0 now runs only as a standalone application, and a new Zotero Connector for Firefox replaces the full Firefox extension. We’ve written a [separate post](https://www.zotero.org/blog/a-unified-zotero-experience/) explaining this change. Existing Zotero for Firefox users will be automatically upgraded to the Zotero Connector for Firefox within the next few weeks and will need to install Zotero 5.0 to continue accessing their Zotero data locally."

I wonder if Zot2Bib can be updated to support Zotero 5.0? If not, those of us who use Zot2Bib regularly will have to stay with Zotero 4.x as long as we can.

**Comment by GreenGrape80** [comment]
In addition, Zot2Bib seems to no longer work with Firefox 55.0, which marks many add ons as "Legacy" and says that they will definitely all stop working by November 2017 (see below quote).  I upgraded Firefox without thinking about it as a pop-up came up, and didn't realize that I was going to lose Zot2Bib with this upgrade!    

"Note: Starting in Firefox 57, which will be released in November 2017, only add-ons built with this new technology will work in Firefox. These are indicated by the “Compatible with Firefox 57+” label on addons.mozilla.org (AMO). Add-ons built with the old technology are labeled “Legacy” on the about:addons tab."

**Comment by jawj** [comment]
Fairly sure Zot2Bib can't be updated to the new technology, as it relies on an external AppleScript. It might be easy to make it work with Zotero standalone, though — that was certainly possible in the past. I'll try to take a look.

**Comment by GreenGrape80** [comment]
Thanks for the quick reply and for looking into the issue.

Janet

**Comment by vancleve** [comment]
@jawj, let me know if you'd like any help. I played around with Zot2Bib at one point and added the capability to move the downloaded PDF as well ( #1 and [here](https://github.com/vancleve/Zot2Bib) )

**Comment by jawj** [comment]
Hi all. I've made some minor changes and if you follow the new instructions at http://mackerron.com/zot2bib/ you should be able to get it working. Do let me know if not.
