### ISSUE TITLE
Zot2Bib does not seem to work with Zotero 5.0.81 (possibly due to changes introduced in Zotero 5.0.78)

### ISSUE THREAD

**Issue by nathan-artist** [jawj/Zot2Bib#3]
I updated to Zotero 5.0.81 today and found that I couldn't access the Zot2Bib menu in Zotero; I clicked on the Zot2Bib button and the drop-down menu wouldn't appear.

Then I looked at the [Zotero changelog](https://www.zotero.org/support/changelog) and noticed that there is a note in the changes in 5.0.78 (December 1, 2019) that says: "Zotero 5.0.78 includes many internal changes, and some plugins have not yet been updated for compatibility. The most common plugins (ZotFile, Better BibTeX, Zutilo) have been updated."

So I downgraded to Zotero 5.0.77 (I had to replace my Zotero data folder with a backup in order to downgrade—always back up before upgrading!) and found that the menu still works, so I am sticking with Zotero 5.0.77 for now.

I am not using one of the latest supported versions of macOS, so it would be great if somebody else could test this with a recent version of macOS and confirm that the issue can be replicated.

**Comment by jawj** [comment]
Thanks. Yes, I'm aware of this problem. I am halfway to fixing it, but I'm waiting for the Zotero developers to respond to couple of questions on their mailing list. Hopefully we'll be up and running again soon.

**Comment by jawj** [comment]
This should finally be fixed! I'm using Zot2Bib again with the latest Firefox and Zotero (standalone).
