### ISSUE TITLE
Zot2Bib stopped working on macOS 10.14.6 

### ISSUE THREAD

**Issue by jandhau** [jawj/Zot2Bib#4]
I can't seem to get Zot2Bib to open and import into BibDesk anymore, no matter if I choose a predetermined bib file or choose New Bibliography. 

It worked fine up until last week.  I tried past versions of BibDesk, but to no avail.  
The only change on my system was the update from macOS 10.14.5 to 10.14.6 (I'm still on Mojave). 
Could that have caused it?  

Any suggestions?  

(Because of issue #3 I'm still using Zotero 5.0.77.  BibDesk is version 1.7.6.)

**Comment by jawj** [comment]
This should finally be fixed! I'm using Zot2Bib again with the latest Firefox and Zotero (standalone).
